export const PROJECTS = [
  {
    num: "01",
    title: "Tap-it Web",
    category: "Next.js",
    desc: "Marketing site for Tap-it, a web studio offering website building, redesigns, custom software, and e-shops. Features Tap-it Fitness OS, a gym check-in and membership SaaS, as the flagship case study.",
    tech: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Framer Motion"],
    awards: [],
    image: "/images/projects/tapit.svg",
    link: "https://github.com/Cajam11/Tap-it-Web",
    linkText: "View Project →",
  },
  {
    num: "02",
    title: "MARO Jewellery",
    category: "Next.js",
    desc: "Single-page showcase website for a handmade jewellery brand, presenting 70+ unique pieces with fluid animations and a smart one-click contact system built on Resend.",
    tech: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
    awards: [],
    image: "/images/projects/maro.svg",
    link: "https://github.com/Cajam11/MARO_jewllery",
    linkText: "View Project →",
  },
  {
    num: "03",
    title: "Scratchcard Invites",
    category: "Next.js",
    desc: "Graduation invite platform with a public class tableau, private guest links protected by a hidden phrase, and an interactive scratch-to-reveal invite card exportable to PNG.",
    tech: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase"],
    awards: [],
    image: "/images/projects/scratchcard.svg",
    link: "https://github.com/Cajam11/Scratchcard-invites",
    linkText: "View Project →",
  },
  {
    num: "04",
    title: "Survix - Survey System",
    category: "Node.js",
    desc: "Web-based survey system for creating, managing, and analyzing surveys, built on Node.js and Express with a MySQL database and a documented REST API.",
    tech: ["Node.js", "Express", "MySQL", "JavaScript", "HTML", "CSS"],
    awards: [],
    image: "/images/projects/survix.svg",
    link: "https://github.com/Cajam11/Survix",
    linkText: "View Project →",
  },
  {
    num: "05",
    title: "User Management Technical Test",
    category: "Next.js",
    desc: "Technical assessment project: a user management app with a MySQL-backed data layer, covering user records with addresses and photos in a typed Next.js codebase.",
    tech: ["Next.js", "TypeScript", "MySQL"],
    awards: [],
    image: "/images/projects/technical-test.svg",
    link: "https://github.com/Cajam11/Technical-test",
    linkText: "View Project →",
  },
  {
    num: "06",
    title: "Angular Web App",
    category: "Angular",
    desc: "Angular web application with login, dashboard, user detail views, and history tracking, structured into standalone components with routing.",
    tech: ["Angular", "TypeScript", "HTML", "CSS"],
    awards: [],
    image: "/images/projects/angular-app.svg",
    link: "https://github.com/Cajam11/Web-App-Angular",
    linkText: "View Project →",
  },
  {
    num: "07",
    title: "Blackjack Casino",
    category: "Python",
    desc: "GUI Blackjack game built with Python and Tkinter, with card graphics, win/loss statistics tracking, fullscreen mode, and a dealer AI following official casino rules.",
    tech: ["Python", "Tkinter"],
    awards: [],
    image: "/images/projects/blackjack.svg",
    link: "https://github.com/Cajam11/Blackjack",
    linkText: "View Project →",
  },
  {
    num: "08",
    title: "Hangman",
    category: "Python",
    desc: "Classic Hangman game with a Tkinter GUI, clickable alphabet, progressive drawing, light/dark mode, and automatic save & resume of game state.",
    tech: ["Python", "Tkinter"],
    awards: [],
    image: "/images/projects/hangman.svg",
    link: "https://github.com/Cajam11/Hangman",
    linkText: "View Project →",
  },
  {
    num: "09",
    title: "Fastest Way",
    category: "Python",
    desc: "Python program for finding the fastest route between points - an exercise in shortest-path logic and algorithmic problem solving.",
    tech: ["Python"],
    awards: [],
    image: "/images/projects/fastest-way.svg",
    link: "https://github.com/Cajam11/Fastest-way",
    linkText: "View Project →",
  },
  // ===== DIGITAL / CREATIVE (placeholders - replace with your real design work) =====
  {
    num: "01",
    title: "Brand & Visual Identity",
    category: "Digital",
    desc: "Logos, brand marks, and visual identity work created in Photoshop and Illustrator for personal and client projects.",
    tech: ["Digital", "Branding", "Illustrator"],
    awards: [],
    image: "/images/digital/branding.svg",
    link: "https://github.com/Cajam11",
    linkText: "View Project →",
  },
  {
    num: "02",
    title: "UI/UX Design in Figma",
    category: "Digital",
    desc: "Interface designs and prototypes crafted in Figma - from wireframes to polished, developer-ready screens.",
    tech: ["Digital", "Figma", "UI/UX"],
    awards: [],
    image: "/images/digital/uiux.svg",
    link: "https://github.com/Cajam11",
    linkText: "View Project →",
  },
  {
    num: "03",
    title: "Creative Content",
    category: "Digital",
    desc: "Graphics, social media visuals, and creative content produced with Photoshop and Illustrator.",
    tech: ["Digital", "Photoshop", "Content"],
    awards: [],
    image: "/images/digital/creative.svg",
    link: "https://github.com/Cajam11",
    linkText: "View Project →",
  },
];

export const TECHNICAL_CATEGORIES = [
  "ALL",
  "NEXT.JS",
  "ANGULAR",
  "NODE.JS",
  "PYTHON",
  "OTHER",
];

export const DIGITAL_CATEGORIES = [
  "ALL",
  "DIGITAL",
];
